# .github/FUNDING.yml
github: [Cyb3rShr3k]   # GitHub Sponsors
buy_me_a_coffee: yourusername    # Buy Me a Coffee
patreon: yourusername            # Patreon
open_collective: yourproject     # Open Collective
custom: ["https://paypal.me/yourusername"]
